[http]
    [http.routers]

        [http.routers.api-router]
            rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
            entryPoints = ["web"]
            middlewares = ["user-auth"]
            service = "api@internal"

        [http.routers.counters-app-router]
            rule = "PathPrefix(`/app/cnts/be`)"
            entryPoints = ["web"]
            middlewares = ["counters-app-mw"]
            service = "counters-app"



