{
 "title": "DailyProduction",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "UserStartDate", "label": "DATA INIZIO (DD/MM/YYYY)" },
   {
    "name": "UserDays",
    "label": "STORICO PRODUZIONE - GIORNI:",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,30"
   },
   { "name": "MaxDays", "query": "30" },
   {
    "name": "Days",
    "query": "SELECT IF(${UserDays}<=${MaxDays}, ${UserDays}, ${MaxDays}); "
   },
   {
    "name": "DisplayDateFrom",
    "query": "SELECT (\nDATE_FORMAT( \"${StartDate}\" , \"%d/%m/%Y\" )\n); "
   },
   {
    "name": "EndDate",
    "query": "SELECT CONCAT( IF(\"${UserStartDate}\"=\"\",\nCURDATE(),\nDATE_ADD(STR_TO_DATE( \"${UserStartDate}\" , \"%d/%m/%Y\" ), INTERVAL ${Days}-1 DAY)\n));"
   },
   {
    "name": "StartDate",
    "query": "SELECT CONCAT(IF(\"${UserStartDate}\"=\"\",\nDATE_SUB(CURDATE(), INTERVAL ${Days}-1 DAY),\nSTR_TO_DATE( \"${UserStartDate}\" , \"%d/%m/%Y\" )\n)); "
   },
   {
    "name": "DisplayDateTo",
    "query": "SELECT (\nDATE_FORMAT( \"${EndDate}\" , \"%d/%m/%Y\" )\n); "
   }
  ]
 },
 "panels": [
  {
   "title": "TOTALE MOTORI PER TURNO - DAL $DisplayDateFrom AL $DisplayDateTo",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate,\"INGRESSATI\" As X,SUM(Value) as A FROM counters.DailyWorkShiftCounters\r\nWHERE  WorkShift = 'A' AND DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\n"
    },
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate,\"INGRESSATI\" As X,SUM(Value) as B FROM counters.DailyWorkShiftCounters\r\nWHERE  WorkShift = 'B' AND DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\n"
    },
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate,\"INGRESSATI\" As X,SUM(Value) as C FROM counters.DailyWorkShiftCounters\r\nWHERE  WorkShift = 'C' AND DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\n"
    }
   ]
  },
  {
   "title": "TOTALE MOTORI - DAL $DisplayDateFrom AL $DisplayDateTo",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"INGRESSATI\" as Op , SUM(Value) FROM counters.DailyCounters\r\nWHERE  DailyCounters.Group = 'CNTS_GLOBAL' AND DailyCounters.Name = 'ITEMS_IN' AND DailyCounters.Source = 'STAZIONE_INGRESSO_MOTORI' \r\nAND DailyCounters.RefDate >= '${StartDate}' AND DailyCounters.RefDate <= '${EndDate}'\r\n"
    }
   ]
  },
  {
   "title": "MOTORI IN INGRESSO PER GIORNO - DAL $DisplayDateFrom AL $DisplayDateTo",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%d/%m') as \"Data\", Value as \"Turno A Ingressati\" \r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\nAND DailyWorkShiftCounters.WorkShift = 'A' order by RefDate asc;"
    },
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%d/%m') as \"Data\", Value as \"Turno B Ingressati\" \r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\nAND DailyWorkShiftCounters.WorkShift = 'B' order by RefDate asc;"
    },
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%d/%m') as \"Data\", Value as \"Turno C Ingressati\" \r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\nAND DailyWorkShiftCounters.WorkShift = 'C' order by RefDate asc;"
    }
   ]
  },
  {
   "title": "COLOR TEXT - DAL $DisplayDateFrom AL $DisplayDateTo",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE('${StartDate}', \"%Y-%m-%d\") as RefDate, \r\n       CONCAT('Turno: ', DailyWorkShiftCounters.WorkShift, ' - Colore: ', DailyWorkShiftCounters.Name) as turnoEcolore,\r\n       SUM(DailyWorkShiftCounters.Value) as A \r\nFROM counters.DailyWorkShiftCounters\r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_COLORS'  \r\n  AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\n  AND DailyWorkShiftCounters.RefDate >= '${StartDate}' \r\n  AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\nGROUP BY WorkShift, DailyWorkShiftCounters.Name"
    }
   ]
  }
 ]
}