{
 "title": "MonthlyProduction",
 "time": { "from": "2024-06-07T09:11:13.913Z", "to": "2024-06-07T09:21:13.913Z" },
 "templating": {
  "list": [
   { "name": "UserStartDate", "label": "DATA INIZIO (MM/YYYY)" },
   { "name": "UserMonths", "label": "STORICO PRODUZIONE - MESI:", "query": "1,2,3,4,5,6,7,8,9,10,11,12" },
   { "name": "MaxMonths", "query": "12" },
   {
    "name": "Months",
    "query": "SELECT IF(${UserMonths}<=${MaxMonths}, ${UserMonths}, ${MaxMonths}); "
   },
   {
    "name": "DisplayDateFrom",
    "query": "SELECT (\nDATE_FORMAT( \"${StartDate}\" , \"%d/%m/%Y\" )\n); "
   },
   {
    "name": "EndDate",
    "query": "SELECT IF(\"${UserStartDate}\"=\"\",\nCURDATE(),\nDATE_ADD(DATE_FORMAT(STR_TO_DATE(CONCAT(\"01/\",\"${UserStartDate}\") , \"%d/%m/%Y\"), \"%Y-%m-%d\"), INTERVAL  ${Months}-1 MONTH)\n);"
   },
   {
    "name": "StartDate",
    "query": "SELECT IF(\"${UserStartDate}\"=\"\",\nDATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL ${Months}-1 MONTH), \"%Y-%m-01\"),\nDATE_FORMAT(STR_TO_DATE(CONCAT(\"01/\",\"${UserStartDate}\") , \"%d/%m/%Y\"), \"%Y-%m-%d\")\n); "
   },
   {
    "name": "DisplayDateTo",
    "query": "SELECT (\nDATE_FORMAT( \"${EndDate}\" , \"%d/%m/%Y\" )\n); "
   }
  ]
 },
 "panels": [
  {
   "title": "Color Text ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE('${StartDate}', \"%Y-%m-%d\") as RefDate, \n       CONCAT('Turno: ', DailyWorkShiftCounters.WorkShift, ' - Colore: ', DailyWorkShiftCounters.Name) as turnoEcolore,\n       SUM(DailyWorkShiftCounters.Value) as A \nFROM counters.DailyWorkShiftCounters\nWHERE DailyWorkShiftCounters.Group = 'CNTS_COLORS'  \n  AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\n  AND DailyWorkShiftCounters.RefDate >= '${StartDate}' \n  AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\nGROUP BY WorkShift, DailyWorkShiftCounters.Name\n"
    }
   ]
  },
  {
   "title": "TOTALE MOTORI INGRESSATI Mensile",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate,\"INGRESSATI\" As X,SUM(Value) as A FROM counters.DailyWorkShiftCounters\r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' AND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'"
    }
   ]
  },
  {
   "title": "MOTORI DAL $DisplayDateFrom AL $DisplayDateTo",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%m/%Y') as \"Data\", Value as \"Turno A Ingressati\" \r\nFROM counters.MonthlyWorkShiftCounters \r\nWHERE MonthlyWorkShiftCounters.Group = 'CNTS_GLOBAL' \r\n  AND MonthlyWorkShiftCounters.Name = 'ITEMS_IN' \r\n  AND MonthlyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\n  AND MonthlyWorkShiftCounters.RefDate >= '${StartDate}' AND MonthlyWorkShiftCounters.RefDate <= '${EndDate}'\r\n  AND MonthlyWorkShiftCounters.WorkShift = 'A' \r\norder by RefDate asc;"
    },
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%m/%Y') as \"Data\", Value as \"Turno B Ingressati\" \r\nFROM counters.MonthlyWorkShiftCounters \r\nWHERE MonthlyWorkShiftCounters.Group = 'CNTS_GLOBAL' \r\n  AND MonthlyWorkShiftCounters.Name = 'ITEMS_IN' \r\n  AND MonthlyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\n  AND MonthlyWorkShiftCounters.RefDate >= '${StartDate}' AND MonthlyWorkShiftCounters.RefDate <= '${EndDate}'\r\n  AND MonthlyWorkShiftCounters.WorkShift = 'B' \r\norder by RefDate asc;"
    },
    {
     "rawSql": "SELECT RefDate, DATE_FORMAT(RefDate, '%m/%Y') as \"Data\", Value as \"Turno C Ingressati\" \r\nFROM counters.MonthlyWorkShiftCounters \r\nWHERE MonthlyWorkShiftCounters.Group = 'CNTS_GLOBAL' \r\n  AND MonthlyWorkShiftCounters.Name = 'ITEMS_IN' \r\n  AND MonthlyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\n  AND MonthlyWorkShiftCounters.RefDate >= '${StartDate}' AND MonthlyWorkShiftCounters.RefDate <= '${EndDate}'\r\n  AND MonthlyWorkShiftCounters.WorkShift = 'C' \r\norder by RefDate asc;"
    }
   ]
  },
  {
   "title": "Produttività Totale per Turni MENSILE",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate, SUM(DailyWorkShiftCounters.Value) as \"Turno A\"\r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.WorkShift = 'A' AND DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND \r\nDailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI' \r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\n\r\n"
    },
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate, SUM(DailyWorkShiftCounters.Value) as \"Turno B\"\r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND DailyWorkShiftCounters.Name = 'ITEMS_IN' \r\nAND DailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'\r\nAND DailyWorkShiftCounters.WorkShift = 'B' \r\norder by RefDate asc;"
    },
    {
     "rawSql": "SELECT STR_TO_DATE( '${StartDate}', \"%Y-%m-%d\" ) as REfDate, SUM(DailyWorkShiftCounters.Value) as \"Turno C\"\r\n\r\nFROM counters.DailyWorkShiftCounters \r\nWHERE DailyWorkShiftCounters.WorkShift = 'C' AND DailyWorkShiftCounters.Group = 'CNTS_GLOBAL' AND \r\nDailyWorkShiftCounters.Source = 'STAZIONE_INGRESSO_MOTORI' \r\nAND DailyWorkShiftCounters.RefDate >= '${StartDate}' AND DailyWorkShiftCounters.RefDate <= '${EndDate}'"
    }
   ]
  },
  {
   "title": "Esiti Produzione DA ${StartDate}  A ${EndDate}",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE('${StartDate}', \"%Y-%m-%d\") as RefDate, \n    CONCAT('Esito: ', DailyCounters.Name) as esito,\n    SUM(DailyCounters.Value) as sommaEsito\nFROM \n    counters.DailyCounters\nWHERE \n    DailyCounters.Group = 'CNTS_QUALITY_CHECK'  \n    AND DailyCounters.Source = 'STAZIONE_INGRESSO_MOTORI'\n    AND DailyCounters.RefDate >= '${StartDate}' \n    AND DailyCounters.RefDate <= '${EndDate}'\nGROUP BY \n    DailyCounters.Name\n\n\n"
    }
   ]
  }
 ]
}